export type Film = {
  title: string;
  slug: string;
  status: "In Production" | "Post-Production" | "Coming Soon";
  video: string;
  youtubeId: string | null;
  description: string;
  synopsis: string;
  year: string;
  duration: string;
  director: string;
  cast: string[];
};

export const films: Film[] = [
  {
    title: "Vite",
    slug: "vite",
    status: "In Production",
    video: "/clips/vite.mp4",
    youtubeId: null,
    description: "The story behind the build tool that changed how developers ship for the web.",
    synopsis: "When Evan You set out to solve the frustrations of modern frontend tooling, he didn't just build another bundler — he rethought the entire development experience. Vite emerged from a simple question: why should developers wait? This film follows the creation of a tool that would go on to reshape how millions of developers build for the web, from its origins in the Vue.js ecosystem to its adoption across the entire JavaScript landscape.",
    year: "2026",
    duration: "45 min",
    director: "Josiah Humphrey",
    cast: ["Evan You", "Matias Capeletto", "Anthony Fu", "Patak"],
  },
  {
    title: "Kubernetes",
    slug: "kubernetes",
    status: "Coming Soon",
    video: "/clips/kubernetes.mp4",
    youtubeId: null,
    description: "How a project born inside Google became the operating system of the cloud.",
    synopsis: "Born from Google's internal container orchestration system Borg, Kubernetes was released to the world in 2014. This film traces its journey from an internal Google project to the de facto standard for container orchestration, exploring the people who built it and the decisions that shaped cloud computing as we know it.",
    year: "2026",
    duration: "TBA",
    director: "Josiah Humphrey",
    cast: ["Brendan Burns", "Joe Beda", "Craig McLuckie", "Tim Hockin"],
  },
  {
    title: "React",
    slug: "react",
    status: "In Production",
    video: "/clips/reactjs.mp4",
    youtubeId: null,
    description: "The people and decisions behind the library that reshaped frontend development.",
    synopsis: "In 2013, Facebook open-sourced a JavaScript library that would fundamentally change how we think about building user interfaces. React's component model and virtual DOM were controversial ideas at the time. This film explores the humans behind React — from Jordan Walke's initial prototype to the team that championed it through skepticism, adoption, and evolution into one of the most influential open source projects ever created.",
    year: "2026",
    duration: "52 min",
    director: "Josiah Humphrey",
    cast: ["Jordan Walke", "Dan Abramov", "Sophie Alpert", "Sebastian Markbåge"],
  },
  {
    title: "GraphQL",
    slug: "graphql",
    status: "Post-Production",
    video: "/clips/graphql.mp4",
    youtubeId: null,
    description: "From Facebook's internal tool to the query language powering modern APIs.",
    synopsis: "When Facebook's mobile apps struggled with the limitations of REST APIs, a small team built something different. GraphQL started as an internal tool to solve a specific mobile data-fetching problem and grew into a new paradigm for API design. This documentary follows the people who created, championed, and ultimately open-sourced GraphQL — changing how the industry thinks about data exchange.",
    year: "2025",
    duration: "48 min",
    director: "Josiah Humphrey",
    cast: ["Lee Byron", "Dan Schafer", "Nick Schrock"],
  },
  {
    title: "Node.js",
    slug: "nodejs",
    status: "In Production",
    video: "/clips/nodejs.mp4",
    youtubeId: null,
    description: "The runtime that took JavaScript beyond the browser and into everything.",
    synopsis: "Ryan Dahl's frustration with the limitations of existing web servers led him to create Node.js — a runtime that would take JavaScript from the browser to the server, the desktop, and beyond. This film explores the technical decisions, community conflicts, and personal sacrifices behind the project that unified web development under a single language.",
    year: "2026",
    duration: "55 min",
    director: "Josiah Humphrey",
    cast: ["Ryan Dahl", "Isaac Z. Schlueter", "Mikeal Rogers", "James Snell"],
  },
  {
    title: "Local First",
    slug: "local-first",
    status: "Coming Soon",
    video: "/clips/localfirst.mp4",
    youtubeId: null,
    description: "A movement to put data back in the hands of the people who create it.",
    synopsis: "In an era of cloud-everything, a growing movement of researchers and engineers is asking: what if your data never had to leave your device? Local-first software promises real-time collaboration without centralized servers, true data ownership, and software that works forever. This film follows the thinkers and builders driving this paradigm shift.",
    year: "2026",
    duration: "TBA",
    director: "Josiah Humphrey",
    cast: ["Martin Kleppmann", "Peter van Hardenberg", "Brooklyn Zelenka"],
  },
  {
    title: "Elixir",
    slug: "elixir",
    status: "Post-Production",
    video: "/clips/elixir.mp4",
    youtubeId: null,
    description: "How José Valim created a language built for the demands of real-time systems.",
    synopsis: "José Valim was a core contributor to Ruby on Rails when he began exploring the Erlang virtual machine. What started as a research project became Elixir — a language designed for scalability, fault tolerance, and developer happiness. This film follows Valim's journey from Rails contributor to language creator, and the community that formed around a new way of thinking about concurrent systems.",
    year: "2025",
    duration: "42 min",
    director: "Josiah Humphrey",
    cast: ["José Valim", "Chris McCord", "Andrea Leopardi", "Justin Schneck"],
  },
  {
    title: "Angular",
    slug: "angular",
    status: "In Production",
    video: "/clips/angular.mp4",
    youtubeId: null,
    description: "The framework that brought structure to the chaos of early web applications.",
    synopsis: "Before Angular, building complex web applications was an exercise in managing chaos. Miško Hevery's side project at Google became the first major JavaScript framework — introducing concepts like two-way data binding and dependency injection to the frontend world. This film traces Angular's evolution through its controversial rewrite, the community's response, and its enduring influence on how we build for the web.",
    year: "2026",
    duration: "50 min",
    director: "Josiah Humphrey",
    cast: ["Miško Hevery", "Brad Green", "Igor Minar", "Minko Gechev"],
  },
  {
    title: "Vue.js",
    slug: "vuejs",
    status: "Coming Soon",
    video: "/clips/vuejs.mp4",
    youtubeId: null,
    description: "How Evan You built an alternative that millions of developers chose for themselves.",
    synopsis: "Evan You left Google to build Vue.js full-time, funded entirely by the open source community. Without corporate backing, Vue grew to become one of the most popular JavaScript frameworks in the world. This is the story of independent open source — how one developer's vision, sustained by community support, created a framework that rivals those backed by the biggest tech companies.",
    year: "2026",
    duration: "TBA",
    director: "Josiah Humphrey",
    cast: ["Evan You", "Sarah Drasner", "Guillaume Chau", "Natalia Tepluhina"],
  },
  {
    title: "Python",
    slug: "python",
    status: "In Production",
    video: "/clips/python.mp4",
    youtubeId: null,
    description: "The language that made programming accessible and then conquered everything.",
    synopsis: "Guido van Rossum created Python over a Christmas holiday in 1989, naming it after Monty Python's Flying Circus. Designed for readability and simplicity, Python was initially dismissed by many as a scripting language. Three decades later, it dominates machine learning, data science, web development, and education. This film explores the philosophy, community, and quiet persistence behind Python's extraordinary rise.",
    year: "2026",
    duration: "58 min",
    director: "Josiah Humphrey",
    cast: ["Guido van Rossum", "Brett Cannon", "Carol Willing", "Barry Warsaw"],
  },
  {
    title: "Ember.js",
    slug: "emberjs",
    status: "Post-Production",
    video: "/clips/emberjs.mp4",
    youtubeId: null,
    description: "Convention over configuration — the framework that bet on developer happiness.",
    synopsis: "Yehuda Katz and Tom Dale set out to bring the best ideas from server-side frameworks to JavaScript. Ember.js championed conventions, stability, and long-term thinking in an ecosystem obsessed with the new. This film explores what it means to build a framework that prioritizes its community's productivity over hype — and the trade-offs that come with that commitment.",
    year: "2025",
    duration: "40 min",
    director: "Josiah Humphrey",
    cast: ["Yehuda Katz", "Tom Dale", "Godfrey Chan", "Jen Weber"],
  },
  {
    title: "Ruby on Rails",
    slug: "ruby-on-rails",
    status: "In Production",
    video: "/clips/rails.mp4",
    youtubeId: null,
    description: "The framework that made the web feel like it belonged to independent creators.",
    synopsis: "David Heinemeier Hansson extracted Ruby on Rails from Basecamp in 2004, and the web was never the same. Rails made it possible for small teams and solo developers to build ambitious web applications — democratizing a space previously dominated by enterprise tools. This film explores how Rails shaped a generation of startups, developers, and the culture of modern web development.",
    year: "2026",
    duration: "54 min",
    director: "Josiah Humphrey",
    cast: ["David Heinemeier Hansson", "Tobias Lütke", "Aaron Patterson", "Eileen Uchitelle"],
  },
  {
    title: "Java",
    slug: "java",
    status: "In Production",
    video: "/clips/java.mp4",
    youtubeId: null,
    description: "Write once, run anywhere — the language that powers the enterprise backbone.",
    synopsis: "James Gosling and his team at Sun Microsystems set out to build a language for interactive television. What they created instead was Java — a language and platform that would come to power everything from enterprise backends to Android phones. This film follows Java's journey through Sun's rise and fall, the Oracle acquisition, and its enduring presence in the systems that run the modern world.",
    year: "2026",
    duration: "60 min",
    director: "Josiah Humphrey",
    cast: ["James Gosling", "Brian Goetz", "Mark Reinhold", "Georges Saab"],
  },
  {
    title: "IntelliJ",
    slug: "intellij",
    status: "Coming Soon",
    video: "/clips/intellij.mp4",
    youtubeId: null,
    description: "The IDE that proved developer tools could be intelligent and opinionated.",
    synopsis: "JetBrains built IntelliJ IDEA with a radical premise: the IDE should understand your code. In a world of lightweight text editors, IntelliJ bet on deep code analysis, intelligent refactoring, and opinionated tooling. This film explores how a Czech software company built the IDE that enterprise developers swear by — and the philosophy of developer tooling that drives everything JetBrains creates.",
    year: "2026",
    duration: "TBA",
    director: "Josiah Humphrey",
    cast: ["Maxim Shafirov", "Dmitry Jemerov", "Hadi Hariri"],
  },
  {
    title: "Prometheus",
    slug: "prometheus",
    status: "Post-Production",
    video: "/clips/prometheus.mp4",
    youtubeId: null,
    description: "How an observability tool built at SoundCloud became the standard for monitoring.",
    synopsis: "When SoundCloud's engineers needed better monitoring for their microservices architecture, they built Prometheus. Inspired by Google's Borgmon, it introduced a new approach to metrics collection and alerting. This film follows Prometheus from its creation at SoundCloud through its donation to the Cloud Native Computing Foundation and its adoption as the industry standard for cloud-native monitoring.",
    year: "2025",
    duration: "38 min",
    director: "Josiah Humphrey",
    cast: ["Julius Volz", "Matt Proud", "Björn Rabenstein"],
  },
];

export function getFilmBySlug(slug: string): Film | undefined {
  return films.find((f) => f.slug === slug);
}
