export type FilmStatus = "Released" | "Post-Production" | "In Production" | "Filming" | "Pre-Production" | "Coming Soon" | "Fundraising";

export type Film = {
  title: string;
  slug: string;
  status: FilmStatus;
  video: string;
  youtubeId: string | null;
  description: string;
  synopsis: string;
  year: string;
  duration: string;
  director: string;
  cast: { name: string; role: string }[];
  crew: { name: string; role: string }[];
  technologies: string[];
  sponsors: { name: string }[];
  extras: { title: string; youtubeId: string }[];
  timeline: { label: string; done: boolean }[];
  fundraising: { goal: number; raised: number } | null;
};

export const films: Film[] = [
  {
    title: "Vite",
    slug: "vite",
    status: "Released",
    video: "/clips/vite.mp4",
    youtubeId: "bmWQqAKLgT4",
    description: "The story behind the build tool that changed how developers ship for the web.",
    synopsis: "When Evan You set out to solve the frustrations of modern frontend tooling, he didn't just build another bundler — he rethought the entire development experience. Vite emerged from a simple question: why should developers wait? This film follows the creation of a tool that would go on to reshape how millions of developers build for the web, from its origins in the Vue.js ecosystem to its adoption across the entire JavaScript landscape.",
    year: "2025",
    duration: "45 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Evan You", role: "Creator of Vite & Vue.js" },
      { name: "Matias Capeletto", role: "Vite Core Team" },
      { name: "Anthony Fu", role: "Vite Core Team" },
      { name: "Patak", role: "Vite Core Team" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
      { name: "Marcus Webb", role: "Director of Photography" },
    ],
    technologies: ["Vite", "Vue.js", "JavaScript", "TypeScript", "ESM"],
    sponsors: [{ name: "StackBlitz" }, { name: "Vercel" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Kubernetes",
    slug: "kubernetes",
    status: "Released",
    video: "/clips/kubernetes.mp4",
    youtubeId: "BE77h7dmoQU",
    description: "How a project born inside Google became the operating system of the cloud.",
    synopsis: "Born from Google's internal container orchestration system Borg, Kubernetes was released to the world in 2014. This film traces its journey from an internal Google project to the de facto standard for container orchestration, exploring the people who built it and the decisions that shaped cloud computing as we know it.",
    year: "2022",
    duration: "52 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Brendan Burns", role: "Co-creator of Kubernetes" },
      { name: "Joe Beda", role: "Co-creator of Kubernetes" },
      { name: "Craig McLuckie", role: "Co-creator of Kubernetes" },
      { name: "Tim Hockin", role: "Google, Kubernetes Lead" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Kubernetes", "Docker", "Go", "Cloud Native", "CNCF"],
    sponsors: [{ name: "Google Cloud" }, { name: "Red Hat" }],
    extras: [
      { title: "Behind the Scenes", youtubeId: "318elIq37PE" },
    ],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "React",
    slug: "react",
    status: "Released",
    video: "/clips/reactjs.mp4",
    youtubeId: "8pDqJVdNa44",
    description: "The people and decisions behind the library that reshaped frontend development.",
    synopsis: "In 2013, Facebook open-sourced a JavaScript library that would fundamentally change how we think about building user interfaces. React's component model and virtual DOM were controversial ideas at the time. This film explores the humans behind React — from Jordan Walke's initial prototype to the team that championed it through skepticism, adoption, and evolution into one of the most influential open source projects ever created.",
    year: "2023",
    duration: "52 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Jordan Walke", role: "Creator of React" },
      { name: "Dan Abramov", role: "React Core Team" },
      { name: "Sophie Alpert", role: "Former React Lead" },
      { name: "Sebastian Markbåge", role: "React Core Team" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
      { name: "Marcus Webb", role: "Director of Photography" },
    ],
    technologies: ["React", "JavaScript", "JSX", "Virtual DOM"],
    sponsors: [{ name: "IBM" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "GraphQL",
    slug: "graphql",
    status: "Released",
    video: "/clips/graphql.mp4",
    youtubeId: "783ccP__No8",
    description: "From Facebook's internal tool to the query language powering modern APIs.",
    synopsis: "When Facebook's mobile apps struggled with the limitations of REST APIs, a small team built something different. GraphQL started as an internal tool to solve a specific mobile data-fetching problem and grew into a new paradigm for API design. This documentary follows the people who created, championed, and ultimately open-sourced GraphQL — changing how the industry thinks about data exchange.",
    year: "2019",
    duration: "48 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Lee Byron", role: "Co-creator of GraphQL" },
      { name: "Dan Schafer", role: "Co-creator of GraphQL" },
      { name: "Nick Schrock", role: "Co-creator of GraphQL" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["GraphQL", "API Design", "JavaScript"],
    sponsors: [{ name: "Prisma" }, { name: "Apollo" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Node.js",
    slug: "nodejs",
    status: "Released",
    video: "/clips/nodejs.mp4",
    youtubeId: "LB8KwiiUGy0",
    description: "The runtime that took JavaScript beyond the browser and into everything.",
    synopsis: "Ryan Dahl's frustration with the limitations of existing web servers led him to create Node.js — a runtime that would take JavaScript from the browser to the server, the desktop, and beyond. This film explores the technical decisions, community conflicts, and personal sacrifices behind the project that unified web development under a single language.",
    year: "2024",
    duration: "55 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Ryan Dahl", role: "Creator of Node.js" },
      { name: "Isaac Z. Schlueter", role: "Creator of npm" },
      { name: "Mikeal Rogers", role: "Node.js Foundation" },
      { name: "James Snell", role: "Node.js TSC" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
      { name: "Marcus Webb", role: "Director of Photography" },
    ],
    technologies: ["Node.js", "JavaScript", "V8", "npm", "Deno"],
    sponsors: [{ name: "IBM" }, { name: "Google" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Local First",
    slug: "local-first",
    status: "Fundraising",
    video: "/clips/localfirst.mp4",
    youtubeId: null,
    description: "A movement to put data back in the hands of the people who create it.",
    synopsis: "In an era of cloud-everything, a growing movement of researchers and engineers is asking: what if your data never had to leave your device? Local-first software promises real-time collaboration without centralized servers, true data ownership, and software that works forever. This film follows the thinkers and builders driving this paradigm shift.",
    year: "2026",
    duration: "TBA",
    director: "Josiah Humphrey",
    cast: [
      { name: "Martin Kleppmann", role: "Researcher, University of Cambridge" },
      { name: "Peter van Hardenberg", role: "Ink & Switch" },
      { name: "Brooklyn Zelenka", role: "Fission" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["CRDTs", "Automerge", "Local-first", "P2P"],
    sponsors: [],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: false },
      { label: "Post-Production", done: false },
      { label: "Released", done: false },
    ],
    fundraising: { goal: 50000, raised: 18400 },
  },
  {
    title: "Elixir",
    slug: "elixir",
    status: "Released",
    video: "/clips/elixir.mp4",
    youtubeId: "lxYFOM3UJzo",
    description: "How José Valim created a language built for the demands of real-time systems.",
    synopsis: "José Valim was a core contributor to Ruby on Rails when he began exploring the Erlang virtual machine. What started as a research project became Elixir — a language designed for scalability, fault tolerance, and developer happiness. This film follows Valim's journey from Rails contributor to language creator, and the community that formed around a new way of thinking about concurrent systems.",
    year: "2019",
    duration: "42 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "José Valim", role: "Creator of Elixir" },
      { name: "Chris McCord", role: "Creator of Phoenix" },
      { name: "Andrea Leopardi", role: "Elixir Core Team" },
      { name: "Justin Schneck", role: "Nerves Project" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Elixir", "Erlang", "BEAM", "Phoenix", "OTP"],
    sponsors: [{ name: "DockYard" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Angular",
    slug: "angular",
    status: "Released",
    video: "/clips/angular.mp4",
    youtubeId: "cRC9DlH45lA",
    description: "The framework that brought structure to the chaos of early web applications.",
    synopsis: "Before Angular, building complex web applications was an exercise in managing chaos. Miško Hevery's side project at Google became the first major JavaScript framework — introducing concepts like two-way data binding and dependency injection to the frontend world. This film traces Angular's evolution through its controversial rewrite, the community's response, and its enduring influence on how we build for the web.",
    year: "2025",
    duration: "50 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Miško Hevery", role: "Creator of Angular" },
      { name: "Brad Green", role: "Former Angular Lead" },
      { name: "Igor Minar", role: "Angular Core Team" },
      { name: "Minko Gechev", role: "Angular Team Lead" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Angular", "TypeScript", "JavaScript", "RxJS"],
    sponsors: [{ name: "Google" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Vue.js",
    slug: "vuejs",
    status: "Released",
    video: "/clips/vuejs.mp4",
    youtubeId: "OrxmtDw4pVI",
    description: "How Evan You built an alternative that millions of developers chose for themselves.",
    synopsis: "Evan You left Google to build Vue.js full-time, funded entirely by the open source community. Without corporate backing, Vue grew to become one of the most popular JavaScript frameworks in the world. This is the story of independent open source — how one developer's vision, sustained by community support, created a framework that rivals those backed by the biggest tech companies.",
    year: "2020",
    duration: "34 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Evan You", role: "Creator of Vue.js" },
      { name: "Sarah Drasner", role: "Vue Core Team" },
      { name: "Guillaume Chau", role: "Vue Core Team" },
      { name: "Natalia Tepluhina", role: "Vue Core Team" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Vue.js", "JavaScript", "Composition API"],
    sponsors: [],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Python",
    slug: "python",
    status: "Released",
    video: "/clips/python.mp4",
    youtubeId: "GfH4QL4VqJ0",
    description: "The language that made programming accessible and then conquered everything.",
    synopsis: "Guido van Rossum created Python over a Christmas holiday in 1989, naming it after Monty Python's Flying Circus. Designed for readability and simplicity, Python was initially dismissed by many as a scripting language. Three decades later, it dominates machine learning, data science, web development, and education. This film explores the philosophy, community, and quiet persistence behind Python's extraordinary rise.",
    year: "2025",
    duration: "58 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Guido van Rossum", role: "Creator of Python" },
      { name: "Brett Cannon", role: "Python Core Developer" },
      { name: "Carol Willing", role: "Python Steering Council" },
      { name: "Barry Warsaw", role: "Python Core Developer" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
      { name: "Marcus Webb", role: "Director of Photography" },
    ],
    technologies: ["Python", "CPython", "PyPI", "Machine Learning"],
    sponsors: [{ name: "Google" }, { name: "Microsoft" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Ember.js",
    slug: "emberjs",
    status: "Released",
    video: "/clips/emberjs.mp4",
    youtubeId: "Cvz-9ccflKQ",
    description: "Convention over configuration — the framework that bet on developer happiness.",
    synopsis: "Yehuda Katz and Tom Dale set out to bring the best ideas from server-side frameworks to JavaScript. Ember.js championed conventions, stability, and long-term thinking in an ecosystem obsessed with the new. This film explores what it means to build a framework that prioritizes its community's productivity over hype — and the trade-offs that come with that commitment.",
    year: "2019",
    duration: "40 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Yehuda Katz", role: "Co-creator of Ember.js" },
      { name: "Tom Dale", role: "Co-creator of Ember.js" },
      { name: "Godfrey Chan", role: "Ember Core Team" },
      { name: "Jen Weber", role: "Ember Core Team" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Ember.js", "JavaScript", "Glimmer"],
    sponsors: [],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Ruby on Rails",
    slug: "ruby-on-rails",
    status: "Released",
    video: "/clips/rails.mp4",
    youtubeId: "HDKUEXBF3B4",
    description: "The framework that made the web feel like it belonged to independent creators.",
    synopsis: "David Heinemeier Hansson extracted Ruby on Rails from Basecamp in 2004, and the web was never the same. Rails made it possible for small teams and solo developers to build ambitious web applications — democratizing a space previously dominated by enterprise tools. This film explores how Rails shaped a generation of startups, developers, and the culture of modern web development.",
    year: "2023",
    duration: "54 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "David Heinemeier Hansson", role: "Creator of Ruby on Rails" },
      { name: "Tobias Lütke", role: "CEO of Shopify" },
      { name: "Aaron Patterson", role: "Rails Core Team" },
      { name: "Eileen Uchitelle", role: "Rails Core Team" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
      { name: "Marcus Webb", role: "Director of Photography" },
    ],
    technologies: ["Ruby on Rails", "Ruby", "MVC", "ActiveRecord"],
    sponsors: [{ name: "Shopify" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Java",
    slug: "java",
    status: "In Production",
    video: "/clips/java.mp4",
    youtubeId: null,
    description: "Write once, run anywhere — the language that powers the enterprise backbone.",
    synopsis: "James Gosling and his team at Sun Microsystems set out to build a language for interactive television. What they created instead was Java — a language and platform that would come to power everything from enterprise backends to Android phones. This film follows Java's journey through Sun's rise and fall, the Oracle acquisition, and its enduring presence in the systems that run the modern world.",
    year: "2026",
    duration: "60 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "James Gosling", role: "Creator of Java" },
      { name: "Brian Goetz", role: "Java Language Architect" },
      { name: "Mark Reinhold", role: "Chief Architect, Java Platform" },
      { name: "Georges Saab", role: "VP, Java Platform Group" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Java", "JVM", "Spring", "Android"],
    sponsors: [],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: false },
      { label: "Released", done: false },
    ],
    fundraising: null,
  },
  {
    title: "IntelliJ",
    slug: "intellij",
    status: "Released",
    video: "/clips/intellij.mp4",
    youtubeId: "Kourq_Lz03U",
    description: "The IDE that proved developer tools could be intelligent and opinionated.",
    synopsis: "JetBrains built IntelliJ IDEA with a radical premise: the IDE should understand your code. In a world of lightweight text editors, IntelliJ bet on deep code analysis, intelligent refactoring, and opinionated tooling. This film explores how a Czech software company built the IDE that enterprise developers swear by — and the philosophy of developer tooling that drives everything JetBrains creates.",
    year: "2026",
    duration: "44 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Maxim Shafirov", role: "CEO, JetBrains" },
      { name: "Dmitry Jemerov", role: "VP of Development" },
      { name: "Hadi Hariri", role: "VP of Developer Advocacy" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["IntelliJ IDEA", "JetBrains", "Kotlin", "Java"],
    sponsors: [{ name: "JetBrains" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
  {
    title: "Prometheus",
    slug: "prometheus",
    status: "Released",
    video: "/clips/prometheus.mp4",
    youtubeId: "rT4fJNbfe14",
    description: "How an observability tool built at SoundCloud became the standard for monitoring.",
    synopsis: "When SoundCloud's engineers needed better monitoring for their microservices architecture, they built Prometheus. Inspired by Google's Borgmon, it introduced a new approach to metrics collection and alerting. This film follows Prometheus from its creation at SoundCloud through its donation to the Cloud Native Computing Foundation and its adoption as the industry standard for cloud-native monitoring.",
    year: "2022",
    duration: "38 min",
    director: "Josiah Humphrey",
    cast: [
      { name: "Julius Volz", role: "Co-creator of Prometheus" },
      { name: "Matt Proud", role: "Co-creator of Prometheus" },
      { name: "Björn Rabenstein", role: "Prometheus Maintainer" },
    ],
    crew: [
      { name: "Josiah Humphrey", role: "Director" },
      { name: "Emma Johnston", role: "Producer" },
    ],
    technologies: ["Prometheus", "Grafana", "Cloud Native", "CNCF"],
    sponsors: [{ name: "Red Hat" }],
    extras: [],
    timeline: [
      { label: "Pre-Production", done: true },
      { label: "Filming", done: true },
      { label: "Post-Production", done: true },
      { label: "Released", done: true },
    ],
    fundraising: null,
  },
];

export function getFilmBySlug(slug: string): Film | undefined {
  return films.find((f) => f.slug === slug);
}

export function getRelatedFilms(slug: string, count = 3): Film[] {
  const film = getFilmBySlug(slug);
  if (!film) return films.slice(0, count);
  // Find films sharing the most technologies
  const others = films.filter((f) => f.slug !== slug);
  const scored = others.map((f) => ({
    film: f,
    score: f.technologies.filter((t) => film.technologies.includes(t)).length,
  }));
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, count).map((s) => s.film);
}
